export const TYPES = {
  READ_CATEGORIES_DATA: "READ_CATEGORIES_DATA",
  READ_SUBCATEGORIES_DATA: "READ_SUBCATEGORIES_DATA",
  READ_OFFERS_DATA: "READ_OFFERS_DATA",
  READ_ALL_DATA: "READ_ALL_DATA",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_LOGGED: "GET_LOGGED",
  GET_OFFERS: "GET_OFFERS",
  GET_BEST_SELLERS_BY_CATEGORY: "GET_BEST_SELLERS_BY_CATEGORY"
}