export const TYPES = {
  READ_PRODUCTS_DATA: "READ_PRODUCTS_DATA",
  DELETE_ONE_ELEMENT: "DELETE_ONE_ELEMENT",
  READ_PRODUCT_BY_ID: "READ_PRODUCT_BY_ID",
  MODIFY: "MODIFY",
  CREATE: "CREATE",
  REDIRECT: "REDIRECT"
}